### ISSUE TITLE
Redis Transaction 허용 설정

### ISSUE THREAD

**Issue by dkswnkk** [sou-so/Souso-Server#135]
### Redis Transaction 허용 설정

오전에 있었던 Redis에 FeedViewCount가 없는 문제를 한번 배포되어 있는 클라이언트의 웹페이지를 통해 테스트를 해보았습니다.
- 웹상에서 게시글 삭제 요청.
- 삭제되었다고 팝업 메세지 뜸.
- 그러나 RDBMS에는 삭제되지 않고 데이터가 남아있음.
- 게시글 리스트 조회
- FeedViewCount Exception 발생

위 과정을 통해서 DeleteFeedService에서 일단 일어난 문제가 확실한 것 같고, RDBMS는 삭제가 안된 반면 Redis는 삭제가 된 것을 보면 @Transactional Rollback 처리가 되지 않는 것 같습니다.
또한 스웨거나 포스트맨으로 동작했을 때는 아무 문제 없었는데, 웹상에서 요청한 것은 문제가 발생한 것으로 보아 프론트 측과도 한번 이야기해봐야 할 것 같습니다.
1. https://wildeveloperetrain.tistory.com/137
2. https://sabarada.tistory.com/178
3. https://jjeda.tistory.com/13

## 진행 사항 
- [x] Redis Transaction 허용 설정

**Comment by skmn3** [comment]
그동안 RedisTemplate를 사용한 Transaction이 Rollback을 지원안해서 이런현상이 발생했던 것 같기도하네요

1. https://gompangs.tistory.com/entry/Spring-Redis-Template-Transaction

**Comment by dkswnkk** [comment]
> 그동안 RedisTemplate를 사용한 Transaction이 Rollback을 지원안해서 이런현상이 발생했던 것 같기도하네요
> 
> 1. https://gompangs.tistory.com/entry/Spring-Redis-Template-Transaction

지금 현재 pull request 한 것처럼 하면 Transaction을 사용할 수 있다고 하는데 어떻게 할까요?
